### ISSUE TITLE
feat: determine and impose plan limits

### ISSUE THREAD

**Issue by srizvi** [and-voila/labs#210]
https://github.com/vercel/ai/tree/main/examples/next-openai-rate-limits

**Comment by krrishdholakia** [comment]
Hey @srizvi, I'm the maintainer of [LiteLLM](https://github.com/BerriAI/litellm) working on on our openai-proxy server. 

Would it be useful if we let you set rate limits when creating keys for the proxy? 

Here's how you can create temporary keys for the proxy server today: 

```bash
curl 'http://0.0.0.0:8000/key/generate' \
--h 'Authorization: Bearer sk-1234' \
--d '{"models": ["gpt-3.5-turbo", "gpt-4", "claude-2"], "duration": "20m"}'
```

Docs: https://docs.litellm.ai/docs/simple_proxy#managing-auth---virtual-keys

**Comment by srizvi** [comment]
> Hey @srizvi, I'm the maintainer of [LiteLLM](https://github.com/BerriAI/litellm) working on on our openai-proxy server.
> 
> Would it be useful if we let you set rate limits when creating keys for the proxy?
> 
> Here's how you can create temporary keys for the proxy server today:
> 
> ```shell
> curl 'http://0.0.0.0:8000/key/generate' \
> --h 'Authorization: Bearer sk-1234' \
> --d '{"models": ["gpt-3.5-turbo", "gpt-4", "claude-2"], "duration": "20m"}'
> ```
> 
> Docs: https://docs.litellm.ai/docs/simple_proxy#managing-auth---virtual-keys

Thanks @krrishdholakia ! I will check it out, seems interesting. Appreciate you reaching out.

**Comment by srizvi** [comment]
@ambi-dar / @rradice13 **[Check this out when you have a chance](https://docs.google.com/spreadsheets/d/18b60EvhwS5MK7KvMaW1c0OW6qj6BVGpn8RNjVPZjX_g/edit#gid=1113633339)**
