### ISSUE TITLE
Local install Auth Error

### ISSUE THREAD

**Issue by saashqdev** [and-voila/labs#426]
When I try to login via Google Auth locally I get authorized OK but I get a console screen error message:

```
Error validating datasource `db`: the URL must start with the protocol `prisma://
```

I have all the .env.local database variables set. I notice there's quite a few of them - here's mine:

```
# ::: DATABASE CONFIGURATION :::
DATABASE_URL=postgres://postgres:postgres@localhost:5432/labs
POSTGRES_DATABASE=labs
POSTGRES_HOST=localhost
POSTGRES_PASSWORD=postgres
POSTGRES_PRISMA_URL=prisma://postgres:postgres@localhost:5432/labs
POSTGRES_URL=postgres://postgres:postgres@localhost:5432/labs
POSTGRES_URL_NON_POOLING=w
POSTGRES_USER=postgres
```
I'm not sure there's a protocol called prisma:// at least I've never come across it.  

 also set `DATABASE_URL` in a .env file and commented out the non-pooling URL entry in `schema.prisma`
`
This app is a great idea btw...

**Comment by srizvi** [comment]
Hey @saashqdev, thanks for the report. We use [Prisma Accelerate](https://www.prisma.io/data-platform/accelerate). So this message `Error validating datasource `db`: the URL must start with the protocol `prisma://` is referring to that connection string that begins with `prisma://`.

- Update the prisma client inside `src/lib/db.ts` to use a vanilla prisma connection 
- Use a vanilla posgtres `DATABASE_URL=postgres://postgres:postgres@localhost:5432/labs
POSTGRES_DATABASE=labs` like so as the connection string, which you already have.

**Comment by srizvi** [comment]
Updated the docs @saashqdev in case of any further ambiguities. I'm in the middle of switching things form userId centric to teamId so some Stripe stuff likely broken right now, should all be fixed in a few days, in case you're interested.

**Comment by saashqdev** [comment]
Got it. Thanks so much for the update. D.

**Comment by saashqdev** [comment]
Sorry, quick question: Does it need to be a Vercel Team or can it be any Team?

**Comment by srizvi** [comment]
Anytime, have a great weekend.
